<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260813134032 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create user table with id, email, roles, and password columns';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE "user" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email VARCHAR(180) NOT NULL, roles JSON NOT NULL, password VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql("ALTER TABLE \"user\" ADD name VARCHAR(120) NOT NULL DEFAULT ''");
        $this->addSql("ALTER TABLE \"user\" ADD surname VARCHAR(120) NOT NULL DEFAULT ''");
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE "user"');
    }
}
