assessment_controllers:
    type: attribute
    prefix: /v1/assessment/
    resource:
        path: ../src/Assessment/UI/REST/Controller/
        namespace: App\Assessment\UI\REST\Controller

rest_shared_controllers:
    type: attribute
    prefix: /v1/
    resource:
        path: ../src/Shared/UI/REST/Controller/
        namespace: App\Shared\UI\REST\Controller

web_shared_controllers:
    type: attribute
    resource:
        path: ../src/Shared/UI/WEB/Controller/
        namespace: App\Shared\UI\WEB\Controller
